/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"
#include "lis3dsh.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int buf=1500;
	LedInit(LED_GREEN);
	LedInit(LED_RED);
	LedInit(LED_ORANGE);
	LedInit(LED_BLUE);

	int ret,count;
	LIS_Data val;
	int xt,yt;
	LIS_Init();
	DelayMs(500);
	char str[32];
	SystemInit();
	//DelayMs(500);
	LedBlink(LED_RED,500);
	ret = LIS_DRdy();
	if(ret)
	{
		val = LIS_GetData();
		DelayMs(2000);
		xt = val.x;
		yt = val.y;
		LedBlink(LED_GREEN,500);
		while(1)
		{
			val = LIS_GetData();
			if(val.x<xt-buf && val.y < yt-buf)
			{
				LedOn(LED_GREEN);
				LedOff(LED_RED);
				LedOn(LED_BLUE);
				LedOff(LED_ORANGE);
			}
			else if(val.x<xt-buf && val.y > yt+buf)
			{
				LedOn(LED_GREEN);
				LedOff(LED_RED);
				LedOff(LED_BLUE);
				LedOn(LED_ORANGE);
			}
			else if(val.x>xt+buf && val.y < yt-buf)
			{
				LedOff(LED_GREEN);
				LedOn(LED_RED);
				LedOn(LED_BLUE);
				LedOff(LED_ORANGE);
			}
			else if(val.x>xt+buf && val.y > yt+buf)
			{
				LedOff(LED_GREEN);
				LedOn(LED_RED);
				LedOff(LED_BLUE);
				LedOn(LED_ORANGE);
			}

			else if(val.x>xt+buf)
			{
				LedOff(LED_GREEN);
				LedOn(LED_RED);
				LedOff(LED_BLUE);
				LedOff(LED_ORANGE);
			}

			else if(val.x<xt-buf)
			{
				LedOn(LED_GREEN);
				LedOff(LED_RED);
				LedOff(LED_BLUE);
				LedOff(LED_ORANGE);
			}
			else if(val.y>yt+buf)
			{
				LedOff(LED_GREEN);
				LedOff(LED_RED);
				LedOff(LED_BLUE);
				LedOn(LED_ORANGE);
			}
			else if(val.y<yt-buf)
			{
				LedOff(LED_GREEN);
				LedOff(LED_RED);
				LedOn(LED_BLUE);
				LedOff(LED_ORANGE);
			}
			else
			{
				LedOff(LED_GREEN);
				LedOff(LED_RED);
				LedOff(LED_BLUE);
				LedOff(LED_ORANGE);
			}

		}
	}


	return 0;
}







